version: "3"

services:
  php:
    build:
      context: ./docker/php
      args:
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
        - HOST_IP=${HOST_IP}
    volumes:
      - .:/var/www
      - .:/workspace:cached
      - ./server:/var/www/server
      - ./docker/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    environment:
      - PHP_CS_FIXER_IGNORE_ENV=1

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./server:/var/www/server
      - ./docker/nginx:/etc/nginx/conf.d:cached
    depends_on:
      - php

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev_db
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/db/mysql/data:/var/lib/mysql
      - ./docker/db/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:cached
      - ./docker/db/mysql/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
